### ISSUE TITLE
Add ACL to allow Transactional Ids when declared Stream

### ISSUE THREAD

**Issue by tJouve** [michelin/ns4kafka#144]
In order to allow EOS mecanism for KafkaStream is it possible to automaticaly add Transactional Ids ACL for current namespace prefix

**Comment by twobeeb** [comment]
Yes, as per the Confluent documentation [Required ACL setting for secure Kafka clusters](https://docs.confluent.io/platform/current/streams/developer-guide/security.html#required-acl-setting-for-secure-ak-clusters)
Upon looking in more details, I also see that Confluent suggest a cluster-wide rule 
![image](https://user-images.githubusercontent.com/6431261/146187041-4d99f0ea-83e7-4c2d-b6f5-b8efddf840dc.png)
I will check with Confluent what is the preferred method.

**Comment by twobeeb** [comment]
[KIP-679](https://cwiki.apache.org/confluence/display/KAFKA/KIP-679%3A+Producer+will+enable+the+strongest+delivery+guarantee+by+default) renders obsolete the ACL ``Idempotent_Write`` on ``Cluster`` resource so I won't implement it in ns4kafka.
