### ISSUE TITLE
Kafkactl --reset-offsets option does not create the consumer group if it doesn't exist yet

### ISSUE THREAD

**Issue by clvacher** [michelin/ns4kafka#175]
While this seems like a good safeguard against typos, this feature does exist in the standard kafka-consumer-groups console command and is essential in the following scenarios:

-You want to anticipate your consumers going live and starting at a specific offset instead of just taking their default auto.offset.reset property
-Your consumer is live but hasn't started consuming yet because there are no new data and the auto.offset.reset property is set to latest. The consumer group has never committed a transaction and therefore does not yet have an existing consumer group. If a new record comes in and causes a crash (which can happen frequently in testing environments), the transaction has never been committed, and there's no way to re-consume the data if you're still in latest consumption unless you manually set the offset on the "non-existing" consumer group

**Comment by loicgreffier** [comment]
Duplicate from #171
