### ISSUE TITLE
Changing topic from delete to compact cause InvalidConfigurationException when deploying

### ISSUE THREAD

**Issue by loicgreffier** [michelin/ns4kafka#184]
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: Altering topic configuration from `delete` to `compact` is not currently supported. Please create a new topic with `compact` policy specified instead.

**Comment by twobeeb** [comment]
Interesting, is this for Confluent Cloud only ? I don't recall not being able to do this.

**Comment by loicgreffier** [comment]
Hi @twobeeb, you're right, it depends on Confluent Cloud only: https://docs.confluent.io/cloud/current/clusters/broker-config.html#custom-topic-settings-for-all-cluster-types
