### ISSUE TITLE
kafkactl delete-records broken

### ISSUE THREAD

**Issue by lapsus63** [michelin/ns4kafka#191]
Hello,

We tried to delete-records from our topics of two apps and tried with versions 1.6.1 and 1.7.0 of kafkactl, but we always facing the same issue :

![image](https://user-images.githubusercontent.com/3248718/175295727-369c7df5-f9a3-4031-b337-9ba9eb28445a.png)

Nevertheless, *the delete seems to be performed*

**Comment by loicgreffier** [comment]
Hi @lapsus63, ns4kafka 1.7.0 is not deployed internally yet, so you're facing compatibility issue with current v1.6.1

You should stay on kafkactl 1.6.1

**Comment by loicgreffier** [comment]
@lapsus63, can you confirm you're facing the issue on kafkactl 1.7.0 ? I'll close the issue if you do

**Comment by loicgreffier** [comment]
Confirmed, issue can be closed
