### ISSUE TITLE
Handle unchanged status on schema dry-run / diff

### ISSUE THREAD

**Issue by AlexisSouquiere** [michelin/ns4kafka#341]
## Problem
Suppose that we have a subject with a v1 schema created with ns4kafka
When doing a dry-run / diff with the same schema, kafkactl will return a CHANGED status.
It's because ns4kafka never compares the value of the schema (only if there is a subject present to return CHANGED / CREATED) with the latest schema definition. 

Doing a apply without dry-run won't create a new version the schema are equals so it will return an UNCHANGED status. Behaviour between dry-run and apply without dry-run is different.

## Suggestion
A simple string comparison is not sufficient because we won't take into account formatting changes that could have been done (spaces, tabs, reordering, etc.)

The `kafka-schema-registry-client` dep provides an `AvroSchema` class that we can instantiate with the input schema string and the latest schema definition schema. The constructor normalizes the schema and allows us to compare the two schemas, even if users did some formatting changes. 

My suggestion would be to improve the dry-run comparison (https://github.com/michelin/ns4kafka/blob/master/src/main/java/com/michelin/ns4kafka/controllers/SchemaController.java#L121) by  instantiating 2 AvroSchema instances for the 2 definitions and doing a comparison on the `AvroSchema.canonicalString()` strings

Input schema
```json
{"namespace":"com.michelin.kafka.producer.showcase.avro","type":"record","name":"PersonAvro","fields":[{"name":"firstName","type":["null","string"],"default":null,"doc":"First name of the person"},{"name":"lastName","type":["null","string"],"default":null,"doc":"Last name of the person"},{"name":"dateOfBirth","type":["null",{"type":"long","logicalType":"timestamp-millis"}],"default":null,"doc":"Date of birth of the person"}]}
```

Normalized schema
```json
{"type":"record","name":"PersonAvro","namespace":"com.michelin.kafka.producer.showcase.avro","fields":[{"name":"firstName","type":["null","string"],"doc":"First name of the person","default":null},{"name":"lastName","type":["null","string"],"doc":"Last name of the person","default":null},{"name":"dateOfBirth","type":["null",{"type":"long","logicalType":"timestamp-millis"}],"doc":"Date of birth of the person","default":null}]}
```
## Alternatives Considered
N/A

## Additional Context
N/A

**Comment by loicgreffier** [comment]
Scenario to be validated before implementation:

Schema v1

```json
{"namespace":"com.michelin.kafka.producer.showcase.avro","type":"record","name":"PersonAvro","fields":[{"name":"firstName","type":["null","string"],"default":null,"doc":"First name of the person"},{"name":"lastName","type":["null","string"],"default":null,"doc":"Last name of the person"},{"name":"dateOfBirth","type":["null",{"type":"long","logicalType":"timestamp-millis"}],"default":null,"doc":"Date of birth of the person"}]}
```

and we just swap the order of the `firstName` and `lastName` fields. 

Schema v2

```json
{"namespace":"com.michelin.kafka.producer.showcase.avro","type":"record","name":"PersonAvro","fields":[{"name":"lastName","type":["null","string"],"default":null,"doc":"Last name of the person"},{"name":"firstName","type":["null","string"],"default":null,"doc":"First name of the person"},{"name":"dateOfBirth","type":["null",{"type":"long","logicalType":"timestamp-millis"}],"default":null,"doc":"Date of birth of the person"}]}
```

Based on canonical strings, schemas are different. But when applying the v2 to the Schema Registry, does the Schema Registry is smart enough to detect it is the exact same schema (with fields in different order) or does it creates a new schema ? 

➡️ If a new schema is created, the scenario is OK. (and it seems to be according to my quick tests)
➡️ If no new schema is created, and the v1 is returned from the API call, the scenario is invalid.

____

Think about adding the Confluent repository when using `implementation('io.confluent:kafka-schema-registry-client:7.5.1')`:

```xml
repositories {
    mavenCentral()
    maven {
        url "https://packages.confluent.io/maven"
    }
}
```

**Comment by loicgreffier** [comment]
#344
